routes:
  /podcast/:
    controller: channel
    filter: tag:[hash-podcast]
    data:
      post: page.podcast
    limit: 10
    template: godo-podcast


collections:
  /:
    permalink: /{slug}/
    template: godo-template-featured


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
